Completed Sprint 9
Lsplay2/java-filmorate pull request #3
Opened 2023-05-11 10:51 UTC by Lsplay2

2023-05-12 20:08 UTC, Yang-Pi requested changes

2023-05-12 20:08 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isEmpty() || film.getDescription().getBytes().length > 200
Более удачным решением было бы добавить такие валидации в модели с помощью аннотаций

2023-05-12 20:08 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final LocalDate minDate = LocalDate.of(1895,12,28);
Имя константы нужно писать в верхнем регистре - MIN_DATE

2023-05-12 20:08 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isEmpty() || film.getDescription().getBytes().length > 200
Точно такие же правила валидации ты описал и для post, поэтому имеет смысл вынести их в отдельный метод

2023-05-12 20:08 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Чисто архитектурно было бы удачно сделать один абстрактный класс контроллера, где описать все общее между двумя контролерами. Не пушу это делать, но если интересно..

Посмотри на UserController и FilmController - они довольно похоже.

2023-05-12 20:08 UTC, Yang-Pi commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +            Assertions.assertEquals("Ошибка в одном из полей фильма", e.getMessage());
Можешь использовать assertThrows https://www.baeldung.com/junit-assert-exception

2023-05-15 06:16 UTC, Yang-Pi requested changes

2023-05-15 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
Если имя будет null, то до этого места поток управления даже не дойдет, потому что будет NullPointerException, выкинутый из метода validate

2023-05-15 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName().isEmpty()) {
Я понимаю, почему часть валидации описано в методе validate, а часть тут. Могу предложить сделать 3 метода валидации
1) validate - как сейчас (только исключи падения на null)
2) validateOnCreate - который внутри себя вызывает validate и еще после добавляет свои проверки
3) validateOnUpdate - такой же, как и предыдущий

2023-05-15 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Ошибка в одном из полей фильма");
исключение пусть выкидывается в рамках метода контроллера, но залогировать ошибку с указанием имени поля можно и в рамках метода validate. Потому что поверь, если такой код дебажить при ошибке, то проще сразу видеть, в каком поле проблема, а не искать "одно из полей".

2023-05-15 06:16 UTC, Yang-Pi commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +        Assertions.assertNotEquals(user,userController.users.get(1));
А у тебя этот тест проходит? потому что не могу понять, откуда в контроле могли появиться юзеры, причем как минимум 2

2023-05-15 06:16 UTC, Yang-Pi commented on HELP.md
> +# Getting Started
Вот этот файл наверное лишний

2023-05-15 06:25 UTC, Lsplay2 commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +        Assertions.assertNotEquals(user,userController.users.get(1));
Юзер там 1. Просто они хранятся в Map и id, который является ключей будет равен 1

2023-05-16 06:47 UTC, Yang-Pi approved these changes

2023-05-16 06:47 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isEmpty() || film.getDescription().getBytes().length > 200
1) нужно еще проверить, что описание фильма - это не null
2) у String есть методе length(), поэтому можно не приводить к байтам

2023-05-28 19:44 UTC, merged